name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK 8
        uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: 8
      - name: Cache Gradle
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Build LimboAPI
        run: ./gradlew build
      - name: Upload LimboAPI Plugin
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ElytriumJavaCommons
          path: "build/libs/elytrium-java-commons-*.jar"
